==19891== Memcheck, a memory error detector
==19891== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==19891== Using Valgrind-3.5.0 and LibVEX; rerun with -h for copyright info
==19891== Command: /home/parrish/psi4/obj-plugin/bin/psi4
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C23217746: index (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23207704: expand_dynamic_string_token (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23208001: _dl_map_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2320126D: map_doit (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2320E735: _dl_catch_error (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23201186: do_preload (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204636: dl_main (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2321513A: _dl_sysdep_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204B87: _dl_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23200B27: ??? (in /lib64/ld-2.12.90.so)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2321774B: index (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23207704: expand_dynamic_string_token (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23208001: _dl_map_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2320126D: map_doit (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2320E735: _dl_catch_error (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23201186: do_preload (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204636: dl_main (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2321513A: _dl_sysdep_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204B87: _dl_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23200B27: ??? (in /lib64/ld-2.12.90.so)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2320B6D2: _dl_relocate_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C232033C2: dl_main (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2321513A: _dl_sysdep_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204B87: _dl_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23200B27: ??? (in /lib64/ld-2.12.90.so)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2320B6DB: _dl_relocate_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C232033C2: dl_main (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2321513A: _dl_sysdep_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204B87: _dl_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23200B27: ??? (in /lib64/ld-2.12.90.so)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2320B6D2: _dl_relocate_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C232035D5: dl_main (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2321513A: _dl_sysdep_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204B87: _dl_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23200B27: ??? (in /lib64/ld-2.12.90.so)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2320B6DB: _dl_relocate_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C232035D5: dl_main (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2321513A: _dl_sysdep_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23204B87: _dl_start (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23200B27: ??? (in /lib64/ld-2.12.90.so)
==19891== 
==19891== Invalid read of size 4
==19891==    at 0x3C31AF6B28: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF8DA2: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF934C: _PyArg_ParseTuple_SizeT (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31B22595: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE965A: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB161: PyEval_EvalCode (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFBD01: PyImport_ExecCodeModuleEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFC04D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFD0DE: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==  Address 0x699be68 is 40 bytes inside a block of size 41 alloc'd
==19891==    at 0x4A05E46: malloc (vg_replace_malloc.c:195)
==19891==    by 0x3C31A8C153: PyObject_Malloc (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A9402B: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A94ED4: PyString_Concat (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE2F07: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE91E5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A71C61: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A48FC2: PyObject_Call (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE7F98: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Invalid read of size 4
==19891==    at 0x3C31AF6B3D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF8DA2: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF934C: _PyArg_ParseTuple_SizeT (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31B22595: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE965A: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB161: PyEval_EvalCode (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFBD01: PyImport_ExecCodeModuleEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFC04D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFD0DE: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==  Address 0x699ca0c is 44 bytes inside a block of size 45 alloc'd
==19891==    at 0x4A05F3E: realloc (vg_replace_malloc.c:476)
==19891==    by 0x3C31A94F8C: _PyString_Resize (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE3044: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE91E5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A71C61: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A48FC2: PyObject_Call (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE7F98: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB161: PyEval_EvalCode (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFBD01: PyImport_ExecCodeModuleEx (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Invalid read of size 4
==19891==    at 0x3C31AF6B28: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF883D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF9578: _PyArg_ParseTupleAndKeywords_SizeT (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A69519: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AA46B7: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A48FC2: PyObject_Call (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE965A: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==  Address 0x6a17f78 is 72 bytes inside a block of size 73 alloc'd
==19891==    at 0x4A05F3E: realloc (vg_replace_malloc.c:476)
==19891==    by 0x3C31A94F8C: _PyString_Resize (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE3044: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE91E5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Invalid read of size 4
==19891==    at 0x3C31AF6B3D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF8DA2: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF934C: _PyArg_ParseTuple_SizeT (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31B2199E: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE965A: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB161: PyEval_EvalCode (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFBD01: PyImport_ExecCodeModuleEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==  Address 0x70918f4 is 68 bytes inside a block of size 71 alloc'd
==19891==    at 0x4A05E46: malloc (vg_replace_malloc.c:195)
==19891==    by 0x3C31A8C153: PyObject_Malloc (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A9402B: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A94ED4: PyString_Concat (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE2F07: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE91E5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Invalid read of size 4
==19891==    at 0x3C31AF6B3D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF883D: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AF9578: _PyArg_ParseTupleAndKeywords_SizeT (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A69519: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AA46B7: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A48FC2: PyObject_Call (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE965A: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEA71C: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==  Address 0x70a566c is 76 bytes inside a block of size 79 alloc'd
==19891==    at 0x4A05E46: malloc (vg_replace_malloc.c:195)
==19891==    by 0x3C31A8C153: PyObject_Malloc (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A9402B: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31A94ED4: PyString_Concat (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE2F07: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE91E5: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AEB04C: PyEval_EvalCodeEx (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AE9639: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2320B6D2: _dl_relocate_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23212EA5: dl_open_worker (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2320E735: _dl_catch_error (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C232134E9: _dl_open (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C24200F15: dlopen_doit (in /lib64/libdl-2.12.90.so)
==19891==    by 0x3C2320E735: _dl_catch_error (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2420152B: _dlerror_run (in /lib64/libdl-2.12.90.so)
==19891==    by 0x3C24200FC0: dlopen@@GLIBC_2.2.5 (in /lib64/libdl-2.12.90.so)
==19891==    by 0x3C31B1727F: _PyImport_GetDynLoadFunc (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFEDF7: _PyImport_LoadDynamicModule (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFD0DE: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFD373: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Conditional jump or move depends on uninitialised value(s)
==19891==    at 0x3C2320B6DB: _dl_relocate_object (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C23212EA5: dl_open_worker (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2320E735: _dl_catch_error (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C232134E9: _dl_open (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C24200F15: dlopen_doit (in /lib64/libdl-2.12.90.so)
==19891==    by 0x3C2320E735: _dl_catch_error (in /lib64/ld-2.12.90.so)
==19891==    by 0x3C2420152B: _dlerror_run (in /lib64/libdl-2.12.90.so)
==19891==    by 0x3C24200FC0: dlopen@@GLIBC_2.2.5 (in /lib64/libdl-2.12.90.so)
==19891==    by 0x3C31B1727F: _PyImport_GetDynLoadFunc (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFEDF7: _PyImport_LoadDynamicModule (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFD0DE: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891==    by 0x3C31AFD373: ??? (in /usr/lib64/libpython2.7.so.1.0)
==19891== 
==19891== Syscall param write(buf) points to uninitialised byte(s)
==19891==    at 0x3C23E0E410: __write_nocancel (in /lib64/libpthread-2.12.90.so)
==19891==    by 0x1BB073B: psi::PSIO::rw(unsigned int, char*, psi::psio_address, unsigned long, int) (rw.cc:56)
==19891==    by 0x1BAFA79: psi::PSIO::write(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*) (write.cc:108)
==19891==    by 0x1B95872: psi::Chkpt::wt_irr_labs(char**) (irr_labs.cc:51)
==19891==    by 0xDF90C5: psi::scf::HF::dump_to_checkpoint() (hf.cc:1013)
==19891==    by 0xDF125D: psi::scf::HF::finalize() (hf.cc:309)
==19891==    by 0xE00457: psi::scf::RHF::finalize() (rhf.cc:136)
==19891==    by 0xDFAADE: psi::scf::HF::compute_energy() (hf.cc:1246)
==19891==    by 0xBBEF99: psi::scf::scf(psi::Options&, _object*, _object*) (main.cc:69)
==19891==    by 0xA95C2E: py_psi_scf_callbacks(_object*, _object*) (python.cc:118)
==19891==    by 0xAB656F: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (invoke.hpp:75)
==19891==    by 0xAB2211: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==  Address 0x7193a72 is 2 bytes inside a block of size 5 alloc'd
==19891==    at 0x4A05E46: malloc (vg_replace_malloc.c:195)
==19891==    by 0x1A43E7D: psi::Molecule::irrep_labels() (molecule.cc:2021)
==19891==    by 0xDF909F: psi::scf::HF::dump_to_checkpoint() (hf.cc:1012)
==19891==    by 0xDF125D: psi::scf::HF::finalize() (hf.cc:309)
==19891==    by 0xE00457: psi::scf::RHF::finalize() (rhf.cc:136)
==19891==    by 0xDFAADE: psi::scf::HF::compute_energy() (hf.cc:1246)
==19891==    by 0xBBEF99: psi::scf::scf(psi::Options&, _object*, _object*) (main.cc:69)
==19891==    by 0xA95C2E: py_psi_scf_callbacks(_object*, _object*) (python.cc:118)
==19891==    by 0xAB656F: _object* boost::python::detail::invoke<boost::python::to_python_value<double const&>, double (*)(_object*, _object*), boost::python::arg_from_python<_object*>, boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<double const&> const&, double (*&)(_object*, _object*), boost::python::arg_from_python<_object*>&, boost::python::arg_from_python<_object*>&) (invoke.hpp:75)
==19891==    by 0xAB2211: boost::python::detail::caller_arity<2u>::impl<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAB04D2: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<double (*)(_object*, _object*), boost::python::default_call_policies, boost::mpl::vector3<double, _object*, _object*> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xAF5102: boost::shared_ptr<psi::Matrix>::shared_ptr() (shared_ptr.hpp:182)
==19891==    by 0xF0EB1CA: psi::mad_mp2::MAD_MP2::MAD_MP2(psi::Options&, boost::shared_ptr<psi::PSIO>) (mad_mp2.cc:30)
==19891==    by 0xF0E55C7: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA9588E: boost::detail::shared_count::shared_count() (shared_count.hpp:71)
==19891==    by 0xAF5118: boost::shared_ptr<psi::Matrix>::shared_ptr() (shared_ptr.hpp:182)
==19891==    by 0xF0EB1CA: psi::mad_mp2::MAD_MP2::MAD_MP2(psi::Options&, boost::shared_ptr<psi::PSIO>) (mad_mp2.cc:30)
==19891==    by 0xF0E55C7: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xAF5102: boost::shared_ptr<psi::Matrix>::shared_ptr() (shared_ptr.hpp:182)
==19891==    by 0xF0EB1DC: psi::mad_mp2::MAD_MP2::MAD_MP2(psi::Options&, boost::shared_ptr<psi::PSIO>) (mad_mp2.cc:30)
==19891==    by 0xF0E55C7: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA9588E: boost::detail::shared_count::shared_count() (shared_count.hpp:71)
==19891==    by 0xAF5118: boost::shared_ptr<psi::Matrix>::shared_ptr() (shared_ptr.hpp:182)
==19891==    by 0xF0EB1DC: psi::mad_mp2::MAD_MP2::MAD_MP2(psi::Options&, boost::shared_ptr<psi::PSIO>) (mad_mp2.cc:30)
==19891==    by 0xF0E55C7: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xAF5102: boost::shared_ptr<psi::Matrix>::shared_ptr() (shared_ptr.hpp:182)
==19891==    by 0xF0EB1EE: psi::mad_mp2::MAD_MP2::MAD_MP2(psi::Options&, boost::shared_ptr<psi::PSIO>) (mad_mp2.cc:30)
==19891==    by 0xF0E55C7: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA9588E: boost::detail::shared_count::shared_count() (shared_count.hpp:71)
==19891==    by 0xAF5118: boost::shared_ptr<psi::Matrix>::shared_ptr() (shared_ptr.hpp:182)
==19891==    by 0xF0EB1EE: psi::mad_mp2::MAD_MP2::MAD_MP2(psi::Options&, boost::shared_ptr<psi::PSIO>) (mad_mp2.cc:30)
==19891==    by 0xF0E55C7: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EEB9A: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:273)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EEB9A: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:273)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EEB9A: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:273)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EEB9A: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:273)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDAA2: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:418)
==19891==    by 0xF0EEBDC: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:274)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDACD: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:419)
==19891==    by 0xF0EEBDC: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:274)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xACE17A: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0EEEAF: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:294)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CE0: boost::detail::shared_count::shared_count(boost::detail::shared_count const&) (shared_count.hpp:223)
==19891==    by 0xACE19E: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0EEEAF: psi::mad_mp2::MAD_MP2::J() (mad_mp2.cc:294)
==19891==    by 0xF0EE7D6: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE7F0: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE7F0: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE7F0: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE7F0: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:257)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDAA2: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:418)
==19891==    by 0xF0EF085: psi::mad_mp2::MAD_MP2::Jm12() (mad_mp2.cc:298)
==19891==    by 0xF0EE81A: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDACD: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:419)
==19891==    by 0xF0EF085: psi::mad_mp2::MAD_MP2::Jm12() (mad_mp2.cc:298)
==19891==    by 0xF0EE81A: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xACE17A: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0EF0B6: psi::mad_mp2::MAD_MP2::Jm12() (mad_mp2.cc:299)
==19891==    by 0xF0EE81A: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CE0: boost::detail::shared_count::shared_count(boost::detail::shared_count const&) (shared_count.hpp:223)
==19891==    by 0xACE19E: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0EF0B6: psi::mad_mp2::MAD_MP2::Jm12() (mad_mp2.cc:299)
==19891==    by 0xF0EE81A: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE834: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE834: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE834: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE834: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:258)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EF192: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:303)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EF192: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:303)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EF192: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:303)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EF192: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:303)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDAA2: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:418)
==19891==    by 0xF0EF1D4: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:304)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDACD: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:419)
==19891==    by 0xF0EF1D4: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:304)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xACE17A: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0EFC99: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:364)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CE0: boost::detail::shared_count::shared_count(boost::detail::shared_count const&) (shared_count.hpp:223)
==19891==    by 0xACE19E: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0EFC99: psi::mad_mp2::MAD_MP2::Aia() (mad_mp2.cc:364)
==19891==    by 0xF0EE85E: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE878: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE878: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE878: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE878: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:259)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDAA2: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:418)
==19891==    by 0xF0F0020: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:368)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDACD: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:419)
==19891==    by 0xF0F0020: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:368)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDAA2: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:418)
==19891==    by 0xF0F0043: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:369)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDACD: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:419)
==19891==    by 0xF0F0043: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:369)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678100 is 0 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xACE17A: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xAF4FF1: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0F02C7: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:394)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678110 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CE0: boost::detail::shared_count::shared_count(boost::detail::shared_count const&) (shared_count.hpp:223)
==19891==    by 0xACE19E: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xAF4FF1: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0F02C7: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:394)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0F02C7: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:394)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0F02C7: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:394)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0F02C7: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:394)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0F02C7: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:394)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xACE17A: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0F02E0: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:395)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CE0: boost::detail::shared_count::shared_count(boost::detail::shared_count const&) (shared_count.hpp:223)
==19891==    by 0xACE19E: boost::shared_ptr<psi::Matrix>::shared_ptr(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:169)
==19891==    by 0xF0F02E0: psi::mad_mp2::MAD_MP2::Qia() (mad_mp2.cc:395)
==19891==    by 0xF0EE8A2: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xB0A436: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:112)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE8BC: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xB0A448: void std::swap<psi::Matrix*>(psi::Matrix*&, psi::Matrix*&) (move.h:113)
==19891==    by 0xAFB57A: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:442)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE8BC: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62D18: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:262)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE8BC: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid write of size 8
==19891==    at 0xA62D2A: boost::detail::shared_count::swap(boost::detail::shared_count&) (shared_count.hpp:263)
==19891==    by 0xAFB595: boost::shared_ptr<psi::Matrix>::swap(boost::shared_ptr<psi::Matrix>&) (shared_ptr.hpp:443)
==19891==    by 0xAF5004: boost::shared_ptr<psi::Matrix>::operator=(boost::shared_ptr<psi::Matrix> const&) (shared_ptr.hpp:305)
==19891==    by 0xF0EE8BC: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:260)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDAA2: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:418)
==19891==    by 0xF0F038D: psi::mad_mp2::MAD_MP2::I() (mad_mp2.cc:399)
==19891==    by 0xF0EE8DF: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:261)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xBBDACD: boost::shared_ptr<psi::Matrix>::operator->() const (shared_ptr.hpp:419)
==19891==    by 0xF0F038D: psi::mad_mp2::MAD_MP2::I() (mad_mp2.cc:399)
==19891==    by 0xF0EE8DF: psi::mad_mp2::MAD_MP2::compute_energy() (mad_mp2.cc:261)
==19891==    by 0xF0E5600: plugin_mad_mp2 (main.cc:44)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==  Address 0x6678120 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CB2: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xA9C419: boost::shared_ptr<psi::Matrix>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0EB3C4: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:34)
==19891==    by 0xF0EB669: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:36)
==19891==    by 0xF0E9F6D: void boost::checked_delete<psi::mad_mp2::MAD_MP2>(psi::mad_mp2::MAD_MP2*) (checked_delete.hpp:34)
==19891==    by 0xF0EB06D: boost::detail::sp_counted_impl_p<psi::mad_mp2::MAD_MP2>::dispose() (sp_counted_impl.hpp:78)
==19891==    by 0xA62C4F: boost::detail::sp_counted_base::release() (sp_counted_base_gcc_x86.hpp:145)
==19891==    by 0xA62CC8: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xF0E7CCB: boost::shared_ptr<psi::mad_mp2::MAD_MP2>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0E5616: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CBE: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xA9C419: boost::shared_ptr<psi::Matrix>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0EB3C4: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:34)
==19891==    by 0xF0EB669: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:36)
==19891==    by 0xF0E9F6D: void boost::checked_delete<psi::mad_mp2::MAD_MP2>(psi::mad_mp2::MAD_MP2*) (checked_delete.hpp:34)
==19891==    by 0xF0EB06D: boost::detail::sp_counted_impl_p<psi::mad_mp2::MAD_MP2>::dispose() (sp_counted_impl.hpp:78)
==19891==    by 0xA62C4F: boost::detail::sp_counted_base::release() (sp_counted_base_gcc_x86.hpp:145)
==19891==    by 0xA62CC8: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xF0E7CCB: boost::shared_ptr<psi::mad_mp2::MAD_MP2>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0E5616: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==  Address 0x6678128 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CB2: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xA9C419: boost::shared_ptr<psi::Matrix>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0EB3D6: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:34)
==19891==    by 0xF0EB669: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:36)
==19891==    by 0xF0E9F6D: void boost::checked_delete<psi::mad_mp2::MAD_MP2>(psi::mad_mp2::MAD_MP2*) (checked_delete.hpp:34)
==19891==    by 0xF0EB06D: boost::detail::sp_counted_impl_p<psi::mad_mp2::MAD_MP2>::dispose() (sp_counted_impl.hpp:78)
==19891==    by 0xA62C4F: boost::detail::sp_counted_base::release() (sp_counted_base_gcc_x86.hpp:145)
==19891==    by 0xA62CC8: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xF0E7CCB: boost::shared_ptr<psi::mad_mp2::MAD_MP2>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0E5616: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CBE: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xA9C419: boost::shared_ptr<psi::Matrix>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0EB3D6: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:34)
==19891==    by 0xF0EB669: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:36)
==19891==    by 0xF0E9F6D: void boost::checked_delete<psi::mad_mp2::MAD_MP2>(psi::mad_mp2::MAD_MP2*) (checked_delete.hpp:34)
==19891==    by 0xF0EB06D: boost::detail::sp_counted_impl_p<psi::mad_mp2::MAD_MP2>::dispose() (sp_counted_impl.hpp:78)
==19891==    by 0xA62C4F: boost::detail::sp_counted_base::release() (sp_counted_base_gcc_x86.hpp:145)
==19891==    by 0xA62CC8: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xF0E7CCB: boost::shared_ptr<psi::mad_mp2::MAD_MP2>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0E5616: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==  Address 0x6678118 is not stack'd, malloc'd or (recently) free'd
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CB2: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xA9C419: boost::shared_ptr<psi::Matrix>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0EB3E8: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:34)
==19891==    by 0xF0EB669: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:36)
==19891==    by 0xF0E9F6D: void boost::checked_delete<psi::mad_mp2::MAD_MP2>(psi::mad_mp2::MAD_MP2*) (checked_delete.hpp:34)
==19891==    by 0xF0EB06D: boost::detail::sp_counted_impl_p<psi::mad_mp2::MAD_MP2>::dispose() (sp_counted_impl.hpp:78)
==19891==    by 0xA62C4F: boost::detail::sp_counted_base::release() (sp_counted_base_gcc_x86.hpp:145)
==19891==    by 0xA62CC8: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xF0E7CCB: boost::shared_ptr<psi::mad_mp2::MAD_MP2>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0E5616: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== Invalid read of size 8
==19891==    at 0xA62CBE: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xA9C419: boost::shared_ptr<psi::Matrix>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0EB3E8: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:34)
==19891==    by 0xF0EB669: psi::mad_mp2::MAD_MP2::~MAD_MP2() (mad_mp2.cc:36)
==19891==    by 0xF0E9F6D: void boost::checked_delete<psi::mad_mp2::MAD_MP2>(psi::mad_mp2::MAD_MP2*) (checked_delete.hpp:34)
==19891==    by 0xF0EB06D: boost::detail::sp_counted_impl_p<psi::mad_mp2::MAD_MP2>::dispose() (sp_counted_impl.hpp:78)
==19891==    by 0xA62C4F: boost::detail::sp_counted_base::release() (sp_counted_base_gcc_x86.hpp:145)
==19891==    by 0xA62CC8: boost::detail::shared_count::~shared_count() (shared_count.hpp:217)
==19891==    by 0xF0E7CCB: boost::shared_ptr<psi::mad_mp2::MAD_MP2>::~shared_ptr() (shared_ptr.hpp:169)
==19891==    by 0xF0E5616: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==  Address 0x6678108 is 8 bytes after a block of size 1,008 alloc'd
==19891==    at 0x4A059DC: operator new(unsigned long) (vg_replace_malloc.c:220)
==19891==    by 0xF0E55AF: plugin_mad_mp2 (main.cc:42)
==19891==    by 0xAD5CAD: py_psi_plugin(std::string) (export_plugins.cc:82)
==19891==    by 0xAD70F4: _object* boost::python::detail::invoke<boost::python::to_python_value<int const&>, int (*)(std::string), boost::python::arg_from_python<std::string> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<int const&> const&, int (*&)(std::string), boost::python::arg_from_python<std::string>&) (invoke.hpp:75)
==19891==    by 0xAD6F44: boost::python::detail::caller_arity<1u>::impl<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> >::operator()(_object*, _object*) (caller.hpp:223)
==19891==    by 0xAD6E32: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (*)(std::string), boost::python::default_call_policies, boost::mpl::vector2<int, std::string> > >::operator()(_object*, _object*) (py_function.hpp:38)
==19891==    by 0x2CB4204: boost::python::objects::py_function::operator()(_object*, _object*) const (py_function.hpp:143)
==19891==    by 0x2CB1ECF: boost::python::objects::function::call(_object*, _object*) const (function.cc:226)
==19891==    by 0x2CB3516: boost::python::objects::(anonymous namespace)::bind_return::operator()() const (function.cc:585)
==19891==    by 0x2CB3F2D: boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:188)
==19891==    by 0x2CA91D5: boost::function0<void>::operator()() const (function_template.hpp:1013)
==19891==    by 0x2CA8D08: boost::python::handle_exception_impl(boost::function0<void>) (errors.cc:25)
==19891== 
==19891== 
==19891== HEAP SUMMARY:
==19891==     in use at exit: 2,977,356 bytes in 23,034 blocks
==19891==   total heap usage: 493,593 allocs, 470,559 frees, 61,713,450 bytes allocated
==19891== 
==19891== LEAK SUMMARY:
==19891==    definitely lost: 48,894 bytes in 31 blocks
==19891==    indirectly lost: 9,990 bytes in 210 blocks
==19891==      possibly lost: 2,638,758 bytes in 18,947 blocks
==19891==    still reachable: 279,714 bytes in 3,846 blocks
==19891==         suppressed: 0 bytes in 0 blocks
==19891== Rerun with --leak-check=full to see details of leaked memory
==19891== 
==19891== For counts of detected and suppressed errors, rerun with: -v
==19891== Use --track-origins=yes to see where uninitialised values come from
==19891== ERROR SUMMARY: 141 errors from 76 contexts (suppressed: 0 from 0)
